version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Api_Reuniao/Dockerfile
    container_name: api_reuniao
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
    ports:
      - "9000:9000"
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: apireuniao
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: laravel_postgres
    environment:
      POSTGRES_DB: apireuniao
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
